/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Negocio.Produto;
import dao.ProdutoDAO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JOÃO VITOR
 */
public class Estoque extends javax.swing.JInternalFrame {

    /**
     * Creates new form Estoque
     */
    ProdutoDAO produtoDAO = new ProdutoDAO();

    public void habilitarComponentes() {
        txtNomeProduto.setEditable(true);
        txtDescricao.setEditable(true);
        txtValorCompra.setEditable(true);
        txtValorVenda.setEditable(true);
        cxQuantidade.setEnabled(true);
        txtUnidadeMedida.setEditable(true);

        btSalvar.setEnabled(true);
        btExcluir.setEnabled(true);
        btCancelar.setEnabled(true);
    }
    
    public void desabilitarComponentes(){
        txtNomeProduto.setEditable(false);
        txtDescricao.setEditable(false);
        txtValorCompra.setEditable(false);
        txtValorVenda.setEditable(false);
        cxQuantidade.setEnabled(false);
        txtUnidadeMedida.setEditable(false);

        btSalvar.setEnabled(false);
        btExcluir.setEnabled(false);
        btCancelar.setEnabled(false);

        txtCodProduto.setText("");
        txtNomeProduto.setText("");
        txtDescricao.setText("");
        txtValorCompra.setText("");
        txtValorVenda.setText("");
        txtUnidadeMedida.setText("");
        cxQuantidade.setValue(0);
    }

    public void popularTabela() {
        DefaultTableModel dtm = (DefaultTableModel) tblProdutos.getModel();
        dtm.setNumRows(0);
        ArrayList<Produto> produtos = produtoDAO.listar();

        for (int i = 0; i < produtos.size(); i++) {
            dtm.addRow(new Object[]{
                produtos.get(i).getCodProduto(),
                produtos.get(i).getNomeProduto(),
                produtos.get(i).getValorCompra(),
                produtos.get(i).getValorVenda(),
                produtos.get(i).getQuantidade()
            });
        }

    }

    public Estoque() {
        initComponents();
        popularTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCodProduto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNomeProduto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescricao = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        txtValorCompra = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtValorVenda = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cxQuantidade = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        txtUnidadeMedida = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblProdutos = new javax.swing.JTable();
        btSalvar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Produtos no estoque");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Pesquisar produtos:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 352, -1));

        jLabel2.setText("Código:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        txtCodProduto.setEditable(false);
        getContentPane().add(txtCodProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 60, -1));

        jLabel3.setText("Nome:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, -1, -1));

        txtNomeProduto.setEditable(false);
        getContentPane().add(txtNomeProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 300, -1));

        jLabel4.setText("Descrição:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, -1));

        txtDescricao.setEditable(false);
        txtDescricao.setColumns(20);
        txtDescricao.setRows(5);
        jScrollPane1.setViewportView(txtDescricao);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 260, -1));

        jLabel5.setText("Preço de compra:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, -1, -1));

        txtValorCompra.setEditable(false);
        getContentPane().add(txtValorCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 120, -1));

        jLabel6.setText("Preço de venda:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, -1, -1));

        txtValorVenda.setEditable(false);
        getContentPane().add(txtValorVenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, 120, -1));

        jLabel7.setText("Quantidade:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, -1));

        cxQuantidade.setEnabled(false);
        getContentPane().add(cxQuantidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 60, -1));

        jLabel8.setText("Unidade de medida:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, -1, -1));

        txtUnidadeMedida.setEditable(false);
        getContentPane().add(txtUnidadeMedida, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, 90, -1));

        tblProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código", "Produto", "Preço de Compra", "Preço de venda", "Qtde."
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProdutosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblProdutos);
        if (tblProdutos.getColumnModel().getColumnCount() > 0) {
            tblProdutos.getColumnModel().getColumn(0).setMinWidth(50);
            tblProdutos.getColumnModel().getColumn(0).setPreferredWidth(50);
            tblProdutos.getColumnModel().getColumn(0).setMaxWidth(50);
            tblProdutos.getColumnModel().getColumn(2).setMinWidth(100);
            tblProdutos.getColumnModel().getColumn(2).setPreferredWidth(100);
            tblProdutos.getColumnModel().getColumn(2).setMaxWidth(100);
            tblProdutos.getColumnModel().getColumn(3).setMinWidth(100);
            tblProdutos.getColumnModel().getColumn(3).setPreferredWidth(100);
            tblProdutos.getColumnModel().getColumn(3).setMaxWidth(100);
            tblProdutos.getColumnModel().getColumn(4).setMinWidth(60);
            tblProdutos.getColumnModel().getColumn(4).setPreferredWidth(60);
            tblProdutos.getColumnModel().getColumn(4).setMaxWidth(60);
        }

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 600, 230));

        btSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/salvar.png"))); // NOI18N
        btSalvar.setText("Salvar");
        btSalvar.setEnabled(false);
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, -1, -1));

        btExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/excluir.png"))); // NOI18N
        btExcluir.setText("Excluir");
        btExcluir.setEnabled(false);
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(btExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 240, -1, -1));

        btCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/cancelar.png"))); // NOI18N
        btCancelar.setText("Cancelar");
        btCancelar.setEnabled(false);
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProdutosMouseClicked
        if (evt.getClickCount() == 2) {
            DefaultTableModel dtm = (DefaultTableModel) tblProdutos.getModel();
            int linha = tblProdutos.getSelectedRow();
            Produto produto = produtoDAO.recuperarPorCodigo((int) tblProdutos.getValueAt(linha, 0));
            txtCodProduto.setText(String.valueOf(produto.getCodProduto()));
            txtNomeProduto.setText(produto.getNomeProduto());
            txtDescricao.setText(produto.getDescricacao());
            txtValorCompra.setText(String.valueOf(produto.getValorCompra()));
            txtValorVenda.setText(String.valueOf(produto.getValorVenda()));
            cxQuantidade.setValue(produto.getQuantidade());
            txtUnidadeMedida.setText(produto.getUnidadeMedida());

            //habilitando componentes
            habilitarComponentes();
        }
    }//GEN-LAST:event_tblProdutosMouseClicked

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        desabilitarComponentes();
    }//GEN-LAST:event_btCancelarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        int opcao = JOptionPane.showConfirmDialog(this, "Deseja realmente excluir o produto " + txtNomeProduto.getText() + "?");
        if (opcao == 0) {
            produtoDAO.excluir(Integer.parseInt(txtCodProduto.getText()));
        }
        desabilitarComponentes();
        popularTabela();
    }//GEN-LAST:event_btExcluirActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        Produto produto = new Produto();
        produto.setCodProduto(Integer.parseInt(txtCodProduto.getText()));
        produto.setNomeProduto(txtNomeProduto.getText());
        produto.setDescricacao(txtDescricao.getText());
        produto.setValorCompra(Double.parseDouble(txtValorCompra.getText().replace(",", ".")));
        produto.setValorVenda(Double.parseDouble(txtValorVenda.getText().replace(",", ".")));
        produto.setQuantidade((int) cxQuantidade.getValue());
        produto.setUnidadeMedida(txtUnidadeMedida.getText());
        produtoDAO.editar(produto);
        
        desabilitarComponentes();
        popularTabela();
    }//GEN-LAST:event_btSalvarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btSalvar;
    private javax.swing.JSpinner cxQuantidade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tblProdutos;
    private javax.swing.JTextField txtCodProduto;
    private javax.swing.JTextArea txtDescricao;
    private javax.swing.JTextField txtNomeProduto;
    private javax.swing.JTextField txtUnidadeMedida;
    private javax.swing.JTextField txtValorCompra;
    private javax.swing.JTextField txtValorVenda;
    // End of variables declaration//GEN-END:variables
}
